class webview {
  String Image = "";
  String Name = "";
  String Nameint = "";
  String Url = "";
  String link = "";
  String info = "";
  String Time = "";
  String Language = "";
  String Language1 = "";
  String Quality = "";
  String Genre = "";
  String Play = "";
  String Video = "";
  webview(
      {this.Image = "",
      this.Name = "",
      this.Video = "",
      this.Url = "",
      this.Play = "",
      this.link = "",
      this.Nameint = "",
      this.info = "",
      this.Language = "",
      this.Language1 = "",
      this.Quality = "",
      this.Genre = "",
      this.Time = ""});
  List<webview> bhargav() {
    List<webview> list = [];
    webview splunk = webview(
        link:
            "https://video.adpushup.com/instream/content/tech/javatpointLongVideo/hls.m3u8",
        Url: "https://static.javatpoint.com/tutorial/splunk/images/splunk.png",
        Name: "Splunk",
        Nameint: "Splunk Tutorial",
        info:
            "Splunk is a software technology that uses the data generated by the computer to track, scan, analyze, and visualize it in real-time. It tracks and read store data as indexer events and various types of log files. It enables us to view data in different Dashboard formats."
            "\n\nSplunk is a program that enables the search and analysis of computer data. It analyzes semi-structured data and logs generated by various processes with proper data modeling as per the need of the IT companies. The user produces the data by means of any device like- web apps, sensors, or computers. It has built-in functionality for defining data types, field separators, and search process optimization. For the searched result, it also provides visualization of data."
            "\n\nStudents, IT developers, and experts in IT infrastructure management who want to develop a strong understanding of basic Splunk concepts must-read study this tutorial. You can attain intermediate expertise in Splunk after completing this tutorial, and quickly draw on your skills to solve more difficult problems."
            "\n\nThe reader should be familiar with the language of querying, like SQL. General awareness of standard operations would be particularly useful when using computer applications such as data storage and retrieval and reading computer programs generated logs."
            "\n\nThere is a variety of benefits that are offered by the Splunk, as follows:"
            "\n\nReal-time screen visibility,\n\nSplunk offers Better Interface.\n\nBy offering instant results, it reduces troubleshooting and time-solving.\n\nIt is the most effective method for the study of root causes.\n\nSplunk permits the generation of graphs, warnings, and dashboards.\n\nSimilar findings can be quickly checked and analyzed using Splunk.\n\nIt enables us to troubleshoot any failure state to improve performance.Helps you to track and make educated decisions on every company measure.\n\nSplunk allows Artificial Intelligence to be incorporated into the data strategy.\n\nHelps you to gather useful Operational Intelligence from your system dataSplunk allows us to recognize any data type such as .\n\ncsv, json, log formats, etc.\n\nProvides the most powerful search and visualization tools to enable all types of users.\n\nAllows us to establish a central server, where Splunk data can be searched from various sources.");
    webview SPSS = webview(
        Url:
            "https://www.it-services.ruhr-uni-bochum.de/mam/images/logos/software/spss.png",
        Nameint: "SPSS Tutorial",
        info:
            "This tutorial provides basic and advanced concepts of SPSS. Our SPSS tutorial is designed for beginners and professionals. In this tutorial, we are going to learn how to write proper SPSS. The aim of SPSS is to provide statistical analysis. Our SPSS tutorial includes all topics of SPSS, such as what is SPSS, SPSS Statistics, Parametric Vs. Non-Parametric Stats, SPSS Variables, SPSS Column and Alignment, Scale of Measurement, SPSS Data File Types, SPSS Compute Variable Function, Data transformation, etc."
            "\n\nIn this tutorial, we are going to understand how to run the data analysis technique in SPSS. SPSS stands for statistic package for social science, but the power and capability go beyond social science students. This tutorial gives us a background understanding and deep knowledge of SPSS."
            "\n\nSPSS develops as a programming language, and it is designed to provide statistical analysis. SPSS is a complex and powerful application which have a graphical and syntactical interface. It is used to provide dozens of functions for managing, analyzing, and presenting data. The statistical capability of SPSS contains a range from simple percentages to complex analyses of the linear models, variances, and multiple regressions. We can range our data from binary variables to logarithmic variables. It provides us an extensive data management functions."
            "\n\nIn this tutorial, we will learn how to write the SPSS program, enter data in SPSS, Data transformation, descriptive statistics, independent sample t-test, creating tables and charts, and exploring several functions for managing our data."
            "\n\nIn this course, we will see everything we need to know about SPSS. The first step of this course actually shows us how to design a questionnaire that suits the SPSS program. After that, we will go a step further into coding our data into SPSS."
            "\n\nThe important part of SPSS is how to choose the right statistical technique in SPSS. We break down the process of choosing the right statistical technique in SPSS by creating a flow chart and a statistical decision tree. Based on the type of question we have, based on the type of variable (Independent variable or dependent variable), and based on the measurement level, we will be able to choose the right test in SPSS. The treatment of data and the choice of the right statistical test depend upon the kind of measure we have taken for the variable.",
        Name: "SPSS");
    webview Swagger = webview(
        Url:
            "https://upload.wikimedia.org/wikipedia/commons/a/ab/Swagger-logo.png",
        Nameint: "Swagger Tutorial",
        info:
            "Swagger is the standard way of documenting the Standard APIs. Swagger is helpful when deploying APIs in azure. Swagger is primarily used for documenting API; now the question arises that why document APIs?. The building APIs that are internal in the enterprise or for the public consumption, the theme is the same that the developers usually use in the apps that they are building. For the other developers to be able to use our API, the API must be properly documented; otherwise, how would they know that what are the endpoints exposed by the api and what are the operations supported on those endpoints? What parameters should they pass, and what will they get back? What authentication methods to use?. To answer these questions, it is very important to document the APIs; if you want APIs to be consumed and properly used."
            "\n\nSwagger and Open API specification are the ways to document an API specifying that what exactly APIs can do?."
            "\n\nWhat is API?"
            "\n\nAPI stands for Application Programming Interface. It defines how two pieces of software talk to each other. There are several types of APIs, but the swagger specifically deals with the Web API."
            "\n\nHow do Web APIs work?"
            "\n\nLet's understand the working the Web API through an example. Suppose we opened the Facebook on our phone and made a request to the Facebook server. The request sent to the Facebook server is known as an API request and the Facebook server will send the response known as API response. The server will only send the data, not the whole web page. It is the responsibility of the app to display the web page."
            "\n\nHere, API definition works:"
            "\n\nWhat requests are available"
            "\n\nWhat the response looks like for each request."
            "\n\nSwagger and Open API specification are mainly designed for the Rest API, where Rest is a type of web API. In Rest word, R stands for Representational, S stands for State, and T stands for Transfer."
            "\n\nWhat is API Definition?"
            "\n\nThe API Definition is a file that describes all the things that we can do with an API. It contains all the requests that we can make to an API. It also describes what request to make and how would response look like for each request."
            "\n\nWhy create an API definition?"
            "\n\nThere are several advantages of writing an API definition:"
            "\n\nIt allows you to design the API before implementing it. The developers can review the API before writing the code for the API."
            "\n\nIt also helps in automated testing."
            "\n\nIt can automatically create a code in several languages."
            "\n\nIt can also be used to generate the documentation automatically.",
        Name: "Swagger");
    webview Transact = webview(
        Url:
            "https://cdn.educba.com/academy/wp-content/uploads/2019/02/T-SQL-Commands.jpg",
        Nameint: "Transact Tutorial",
        info:
            "T-SQL (Transact SQL) tutorial is designed for both beginners and professionals. T-SQL expands the SQL to include procedural programming, local variables, string processing, data processing, and mathematics."
            "\n\nOur tutorial provides the basic and advanced concept of T-SQL."
            "\n\nT-SQL (Transact-SQL) is the extension of SQL (Structured Query Language) language. This tutorial covers the core concepts of T-SQL. It covers various functions, procedures, indexes, and transactions, which are related to this topic. Each topic is explained with the help of examples."
            "\n\nWhat is T-SQL?"
            "\n\nIn the year the 1970s, the language 'SEQUEL' (structured English query language), was developed by IBM. After some time, SEQUEL was renamed to 'SQL' which stands for Structured Query Language."
            "\n\nANSI approved SQL in the year of 1986, and after that, in 1987, International Standard Organization (ISO) authorized it."
            "\n\nDifferent RDBMS vendors developed their database language to extending SQL for their products."
            "\n\nT-SQL is known as Transact Structured Query Language, which is the product of Microsoft."
            "\n\nEach variable, column, and expression in SQL is the data type in SQL Server. The data types are used when we create tables. We use the data type for the column of the table based on its requirements."
            "\n\nT-SQL expands the SQL to include procedural programming, local variables, string processing, data processing, and mathematics."
            "\n\nComparison chart of SQL and T-SQL"
            "\n\nBASIS FOR COMPARISON  SQL  T-SQL"
            "\n\nLanguage  Non-procedural Procedural"
            "\n\nFeature Open-source  Proprietary feature"
            "\n\nFunctions provided  Data manipulation and data controlling Local variable and procedural programming language"
            "\n\nQuery submission of both  One by one submission  transfer in bulk"
            "\n\nThe most popular T-SQL statement is stored procedure, which is compiled and stored by the T-SQL code. Stored procedure are executed when they called."
            "\n\nUser-defined functions are the example of the Transact-SQL statement."
            "\n\n",
        Name: "Transact-SQL");
    webview Tumbir = webview(
        Url:
            "https://static.javatpoint.com/tutorial/tumblr/images/tumblr-tutorial.png",
        Nameint: "Tumbir Tutorial",
        info:
            "Tumblr is a social media network and blogging tool launched in 2007 and purchased by Yahoo in 2013. It helps users to publish short blog posts. It is similar to other social media platforms like Twitter, Facebook, Pinterest, and Instagram. It offers various unique opportunities to reach the target audience using content, photos, videos, audios, animated GIFs, and links."
            "\n\nWhy Tumblr?"
            "\n\nAs we all know, Tumblr becomes one of the most popular social media and blogging platform for users to upload posts."
            "\n\nThere are the following reasons to use Tumblr -"
            "\n\n1. Post Interesting contents"
            "\n\nTumblr allows us to post several interesting content such as text, images, chat messages, links, quotes, video clips, audio clips, and animated GIFs to attract the audience."
            "\n\n2. Advanced Email and Mobile Publishing"
            "\n\nTumblr has an excellent email and mobile publishing system that helps users to easily post new good looking content to a Tumblog. Tumblr also uses a Markdown tool that converts text to html. Tumblr helps you to publish audio files, quotes, pictures, email messages, and SMS with the proper formatting."
            "\n\n3. Fastest growing platform"
            "\n\nTumblr is one of the fastest-growing social media platforms. Currently, it is used by more than 20.3 million users. According to a survey, per day, 80 million posts are published on Tumblr."
            "\n\n4. Portfolio"
            "\n\nTumblr uses straightforward UI with its flexible themes that make Tumblr as a great place to display portfolio. Tumblr also uses a writing portfolio as it comes with specific tags to help employers."
            "\n\n5. Upload media directly"
            "\n\nTumblr allows you to upload media like photos, videos, audios, and animated graphics directly without the need for external hosting sites, plugins, and applications.",
        Name: "Tumbir");
    webview ReactJS = webview(
        Url:
            "https://static.javatpoint.com/tutorial/reactjs/images/reactjs-tutorial.png",
        Nameint: "ReactJS Tutorial",
        info:
            "ReactJS tutorial provides basic and advanced concepts of ReactJS. Currently, ReactJS is one of the most popular JavaScript front-end libraries which has a strong foundation and a large community."
            "\n\nReactJS is a declarative, efficient, and flexible JavaScript library for building reusable UI components. It is an open-source, component-based front end library which is responsible only for the view layer of the application. It was initially developed and maintained by Facebook and later used in its products like WhatsApp & Instagram."
            "\n\nOur ReactJS tutorial includes all the topics which help to learn ReactJS. These are ReactJS Introduction, ReactJS Features, ReactJS Installation, Pros and Cons of ReactJS, ReactJS JSX, ReactJS Components, ReactJS State, ReactJS Props, ReactJS Forms, ReactJS Events, ReactJS Animation and many more."
            "\n\nWhy we use ReactJS?"
            "\n\nThe main objective of ReactJS is to develop User Interfaces (UI) that improves the speed of the apps. It uses virtual DOM (JavaScript object), which improves the performance of the app. The JavaScript virtual DOM is faster than the regular DOM. We can use ReactJS on the client and server-side as well as with other frameworks. It uses component and data patterns that improve readability and helps to maintain larger apps."
            "\n\nPrerequisite"
            "\n\nBefore learning ReactJS in-depth, you must have a good knowledge of JavaScript, HTML5, and CSS. The knowledge of ECMAScript 2015 syntax can also be helpful."
            "\n\nAudience"
            "\n\nWe have developed this ReactJS tutorial for beginners and professionals both. We will try to introduce every concept with simple code examples that you can be easily understood. After completing all the sections, you can work confidently with ReactJS."
            "\n\nProblems"
            "\n\nWe assure you that you will not find any problem in our ReactJS tutorial. But, if you find any mistake, you can post it in our comment section.",
        Name: "ReactJS");
    webview Regesx = webview(
        Url:
            "https://static.javatpoint.com/tutorial/regex/images/regex-tutorial.png",
        Nameint: "Regesx Tutorial",
        info:
            "The term Regex stands for Regular expression. The regex or regexp or regular expression is a sequence of different characters which describe the particular search pattern. "
            "\n\nIt is also referred/called as a Rational expression.It is mainly used for searching and manipulating text strings. In simple words, you can easily search the pattern and replace them with the matching pattern with the help of regular expression."
            "\n\nThis concept or tool is used in almost all the programming or scripting languages such as PHP, C, C++, Java, Perl, JavaScript, Python, Ruby, and many others. It is also used in word processors such as word which helps users for searching the text in a document, and also used in various IDEs."
            "\n\nThe pattern defined by the regular expression is applied to the given string or a text from left to right."
            "\n\nRegular Expression Characters"
            "\n\nThere are following different type of characters of a regular expression:"
            "\n\nMetacharacters"
            "\n\nQuantifier"
            "\n\nGroups and Ranges"
            "\n\nEscape Characters or character classes",
        Name: "Regesx");
    webview ReinforcementLearning = webview(
        Url:
            "https://static.javatpoint.com/tutorial/reactjs/images/reactjs-tutorial.png",
        Nameint: "Reinforcement Learning Tutorial",
        info:
            "Our Reinforcement learning tutorial will give you a complete overview of reinforcement learning, including MDP and Q-learning. In RL tutorial, you will learn the below topics:"
            "\n\nWhat is Reinforcement Learning?"
            "\n\nReinforcement Learning is a feedback-based Machine learning technique in which an agent learns to behave in an environment by performing the actions and seeing the results of actions. For each good action, the agent gets positive feedback, and for each bad action, the agent gets negative feedback or penalty."
            "\n\nIn Reinforcement Learning, the agent learns automatically using feedbacks without any labeled data, unlike supervised learning."
            "\n\nSince there is no labeled data, so the agent is bound to learn by its experience only."
            "\n\nRL solves a specific type of problem where decision making is sequential, and the goal is long-term, such as game-playing, robotics, etc."
            "\n\nThe agent interacts with the environment and explores it by itself. The primary goal of an agent in reinforcement learning is to improve the performance by getting the maximum positive rewards."
            "\n\nThe agent learns with the process of hit and trial, and based on the experience, it learns to perform the task in a better way. Hence, we can say that Reinforcement learning is a type of machine learning method where an intelligent agent (computer program) interacts with the environment and learns to act within that. How a Robotic dog learns the movement of his arms is an example of Reinforcement learning."
            "\n\nIt is a core part of Artificial intelligence, and all AI agent works on the concept of reinforcement learning. Here we do not need to pre-program the agent, as it learns from its own experience without any human intervention."
            "\n\nExample: Suppose there is an AI agent present within a maze environment, and his goal is to find the diamond. The agent interacts with the environment by performing some actions, and based on those actions, the state of the agent gets changed, and it also receives a reward or penalty as feedback."
            "\n\nThe agent continues doing these three things (take action, change state/remain in the same state, and get feedback), and by doing these actions, he learns and explores the environment."
            "\n\nThe agent learns that what actions lead to positive feedback or rewards and what actions lead to negative feedback penalty. As a positive reward, the agent gets a positive point, and as a penalty, it gets a negative point.",
        Name: "Reinforcement Learning");
    webview RProgramming = webview(
        Url:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/R_logo.svg/2560px-R_logo.svg.png",
        info:
            "R Programming Tutorial is designed for both beginners and professionals. Our tutorial provides all the basic and advanced concepts of data analysis and visualization."
            "\n\nR is a software environment which is used to analyze statistical information and graphical representation. R allows us to do modular programming using functions."
            "\n\nOur R tutorial includes all topics of R such as introduction, features, installation, rstudio ide, variables, datatypes, operators, if statement, vector, data handing, graphics, statistical modelling, etc. This programming language was named R, based on the first name letter of the two authors (Robert Gentleman and Ross Ihaka)."
            "\n\nWhat is R Programming"
            "\n\nR is an interpreted computer programming language which was created by Ross Ihaka and Robert Gentleman at the University of Auckland, New Zealand.The R Development Core Team currently develops R. It is also a software environment used to analyze statistical information, graphical representation, reporting, and data modeling. R is the implementation of the S programming language, which is combined with lexical scoping semantics."
            "\n\nR not only allows us to do branching and looping but also allows to do modular programming using functions. R allows integration with the procedures written in the C, C++, .Net, Python, and FORTRAN languages to improve efficiency."
            "\n\nIn the present era, R is one of the most important tool which is used by researchers, data analyst, statisticians, and marketers for retrieving, cleaning, analyzing, visualizing, and presenting data."
            "\n\nHistory of R Programming"
            "\n\nThe history of R goes back about 20-30 years ago. R was developed by Ross lhaka and Robert Gentleman in the University of Auckland, New Zealand, and the R Development Core Team currently develops it. This programming language name is taken from the name of both the developers. The first project was considered in 1992. The initial version was released in 1995, and in 2000, a stable beta version was released."
            "\n\nFeatures of R programming"
            "\n\nR is a domain-specific programming language which aims to do data analysis. It has some unique features which make it very powerful. The most important arguably being the notation of vectors. These vectors allow us to perform a complex operation on a set of values in a single command. There are the following features of R programming:"
            "\n\nIt is a simple and effective programming language which has been well developed."
            "\n\nIt is data analysis software."
            "\n\nIt is a well-designed, easy, and effective language which has the concepts of user-defined, looping, conditional, and various I/O facilities."
            "\n\nIt has a consistent and incorporated set of tools which are used for data analysis."
            "\n\nFor different types of calculation on arrays, lists and vectors, R contains a suite of operators."
            "\n\nIt provides effective data handling and storage facility."
            "\n\nIt is an open-source, powerful, and highly extensible software."
            "\n\nIt provides highly extensible graphical techniques."
            "\n\nIt allows us to perform multiple calculations using vectors."
            "\n\nR is an interpreted language.",
        Nameint: "R Programming Tutorial",
        Name: "R Programming");
    webview RxJS = webview(
        Url: "https://static.javatpoint.com/tutorial/rxjs/images/rxjs.png",
        Nameint: "RxJS Tutorial",
        info:
            "RxJS tutorial provides basic and advanced concepts of Reactive Extension for Javascript and Reactive programming. In this tutorial, you will get an overview of Reactive programming, Reactive extension for JavaScript, and its programming concepts, functionalities of RxJS etc. in an easy and simple way. Our RxJS tutorial is designed for beginners and professionals."
            "\n\nRxJS is a JavaScript library that can used with other JavaScript libraries and frameworks such as Angular, ReactJS, Vue.js, Node.js etc. It is supported by JavaScript and also with TypeScript."
            "\n\nOur RxJS tutorial includes all topics of reactive programming, RxJS Latest Updates, RxJS Observables, RxJS Operators, RxJS working etc."
            "\n\nIntroduction to RxJS"
            "\n\nRxJS is an acronym that stands for Reactive Extension for JavaScript. It is a JavaScript library that is used to work with Reactive programming that deals with asynchronous data calls, callbacks and event-based programs. RxJS can be used with other JavaScript libraries such as Angular, ReactJS, Vue.js, Node.js etc. It is supported by JavaScript and also with TypeScript."
            "\n\nWhat is Reactive Programming?"
            "\n\nReactive Programming is a declarative programming paradigm that concerns data streams and the propagation of changes. It is another different way to built software applications. In Reactive Programming, we can easily express static such as arrays or dynamic such as event emitters data streams. It also specifies that an existed inferred dependency within the associated execution model can facilitate the automatic propagation of the changed data flow."
            "\n\nFor example:"
            "\n\nIn the imperative programming declaration, you have seen that a:=b+c would simply mean that a is being assigned as the result of b+c in the instant the expression is evaluated. You can change the values of b and c later, and there would be no effect on the value of a. On the other hand, in reactive programming, the value of a is automatically updated whenever the values of b or c is changed, without the program having to re-execute the statement a:=b+c. In simple means, it determines that a is always assigned with updated values of b+c."
            "\n\nWhat is RxJS?"
            "\n\nThe official website of RxJS has defined it as a library for composing asynchronous and event-based programs by using observable sequences. It provides one core type, the Observable, satellite types (Observer, Schedulers, Subjects) and operators inspired by Array#extras (map, filter, reduce, every, etc.) to allow handling asynchronous events as collections."
            "\n\nRxJS is a JavaScript library that has introduced the concept of reactive programming to the web. In general terms, you can say that RxJS is a Reactive programming language. It provides way to write assembly lines in your software applications. It facilitates you to write software that can be reusable, configurable, and asynchronous."
            "\n\nFeatures of RxJS"
            "\n\nFollowing is the list of essential concepts or primary features of RxJS that are used to solve async event management:"
            "\n\nObservable"
            "\n\nThe observable is used to represent the idea of an invokable collection of future values or events. It can be defined as a function that creates an observer and attaches it to the source where values are expected. The observable examples are clicks, mouse events from a dom element or an Http request, etc."
            "\n\nObserver"
            "\n\nIt is a collection of callbacks that are used to specify how to listen to values delivered by the Observable. It can be specified as an object with next(), error() and complete() methods, that will be executed when you have to interact with observable."
            "\n\nSubscription"
            "\n\nIt is used to represent the execution of an Observable. It is primarily used to cancel the execution. For example, when the observable is created, you have to subscribe to it to execute the observable. It can also be used to cancel the execution.",
        Name: "RxJS");
    webview ReactNative = webview(
        Nameint: "React Native Tutorial",
        info:
            "React Native Tutorial provides basic and advanced concepts of Discrete mathematics. Our React Native Tutorial is designed for beginners and professionals both."
            "\n\nReact Native is a JavaScript Framework which is used to develop mobile applications for iOS and Android."
            "\n\nOur React Native tutorial includes all the topics which help to learn TypeScript. These are React Native Introduction, Environment Setup, First App Hello World, State, Flexbox, Height and Width, TextInput etc."
            "\n\nWhat is React Native?"
            "\n\nReact Native is a JavaScript framework used for developing a real, native mobile application for iOS and Android. It uses only JavaScript to build a mobile application. It is like React, which uses native component rather than using web components as building blocks."
            "\n\nReact Native is based on React, JavaScript library of Facebook, and XML-esque markup (JSX) for developing the user interface. It targets the mobile platform rather than the browser."
            "\n\nWhat are React Native apps?"
            "\n\nReact Native apps are not web application. They are running on a mobile device, and it does not load over the browser. It is also not a Hybrid app that builds over Ionic, Phone Gap, etc. that runs over WebView component. React Native apps are the real native app, the JavaScript code stays as JavaScript, and they run in some extra thread by the compiled app. The user interface and everything are compiled to native code."
            "\n\nHistory of React Native"
            "\n\nFacebook develops the React Native in 2013 for their internal project Hackathon. Later on, it was released publically in January 2015 as React.js, and in March 2015, Facebook announced that React Native is open and available on GitHub."
            "\n\nReact Native was initially developed for the iOS application. However, recently it also supports the Android operating system."
            "\n\nAdvantages of React Native"
            "\n\nThere are several advantages of React Native for building mobile applications. Some of them are given below:"
            "\n\nCross-Platform Usage: Provide facility of Learn once write everywhere, it works for both platform Android as well iOS devices."
            "\n\nClass Performance: The code written in React Native are compiled into native code, which enables it for both operating systems as well as it functions in the same way on both the platforms."
            "\n\nJavaScript: The JavaScript knowledge is used to build native mobile apps."
            "\n\nCommunity: The large community of React and React Native around helps us to find any answer we require."
            "\n\nHot Reloading: Making a few changes in the code of your app will be immediately visible during development. If business logic is changed, its reflection is live reloaded on screen."
            "\n\nImproving with Time: Some features of iOS and Android are still not supported, and the community is always inventing the best practices."
            "\n\nNative Components: We will need to write some platform specific code if we want to create native functionality which is not designed yet."
            "\n\nExistence is Uncertain: As the Facebook develop this framework, its presence is uncertain since it keeps all the rights to kill off the project anytime. As the popularity of React Native rises, it is unlikely to happen.",
        Url:
            "https://static.javatpoint.com/tutorial/react-native/images/react-native-tutorial.png",
        Name: "ReactNative");
    webview PythonDesign = webview(
        Nameint: "Python Design Pattern",
        info:
            "This tutorial will discuss what Design Pattern is and how we can implement using the Python programming language. We will also explain several types of design patterns. We will explore the different approaches to solve the Python problems. Python is a high-level, dynamic type language and popularly used in almost every possible technical domain."
            "\n\nWhat is Design Pattern?"
            "\n\nThe design pattern is a technique which used by the developer to solve the commonly occurring software design. In simple word, it is a predefine pattern to solve a recurring problem in the code. These patterns are mainly designed based on requirements analysis."
            "\n\nThe design pattern is a part of the software development. It is a general repeatable solution for the potential problem in software development. We can follow the patterns details and apply a solution which suits our code."
            "\n\nWe may often confuse the patterns and algorithm, but both are separate approaches to solve repetitive problems. Algorithms generally define the clear set of the solution that can be implemented in some problems, where the patters are high-level description of the solution."
            "\n\nFor example - An algorithm is like a cooking recipe: we have a clear set of ingredients (or set of solutions) to cook something (problems or goals). On the other side, a pattern is like a blueprint: we can see what the result and its features are, but we can modify the order of implementation."
            "\n\nConfiguration of Design Pattern"
            "\n\nIn the below diagram, we describe the basic structure of the design pattern documentation. It is focused on what technology we are using to solve the problems and in what ways."
            "\n\nPattern Name - It is used to define the pattern in a shortly and effectively."
            "\n\nIntent/ Motive - It defines the goal or what the pattern does."
            "\n\nApplicability - It defines all the possible areas where the pattern is applicable."
            "\n\nParticipants and Consequences -It consists of classes and objects used in the design pattern with the list of consequences that exist with the pattern."
            "\n\nHistory of Patterns"
            "\n\nDesign patterns are the set of the solution of common problems in object-oriented design. When the problem's solution is repeated again and again in the various projects, someone eventually puts a name and defines the solution in detail. That is how the pattern gets recognized."
            "\n\nChristopher Alexander has described the concept of the pattern for the first time in the book named A Pattern Language: Towns, Building, and Construction."
            "\n\nThis book defines a 'language' for designing the urban environment. The language is nothing but the patterns."
            "\n\nThe four authors: Erich Gamma, John, Vlissiders, Ralph Johnson, and Richard Helm, were picked the idea of a pattern language. Later, they published the book named Design Patterns: Elements of Reusable Object-Oriented Software. This book contains the concept of design patterns using the programming language."
            "\n\nThe book featured the 23 useful various problems of object-oriented designs; It gained the much popularity among the programmers and became the best seller book very quickly."
            "\n\nInteresting Fact - This book has a very long name so people started to call it The book of gang of four which was soon summarized to simply The GoF book.",
        Url:
            "https://i.pinimg.com/736x/2f/9c/11/2f9c11f9e55efbf1791f12c06d60729b.jpg",
        Name: "Python Design");
    webview PythonPillow = webview(
        Nameint: "Python Pillow Tutorial",
        info:
            "As technology emerges day by day, digital images can be an indispensable source of receiving data. We encounter a lot of digital images in daily life. However, these pictures can be related to anything."
            "\n\nIn the programming world, we can process digital images using various libraries or tools. In this article, we will learn about one of the popular tools of Python is Pillow. However, Python provides many other useful libraries such as OpenCV, Python Image Library (PIL), and Scikit-image. This article completely focuses on the Python Pillow module (PIL)."
            "\n\nBefore dive deep into this topic, let's understand image processing."
            "\n\nWhat is Image Processing?"
            "\n\nImage processing is a method of analyzing and manipulating digital images. The main goal is to extracting some information that can be used somewhere else. Let's make it simple to understand with a real-life example."
            "\n\nFor example - Nowadays, CCTV cameras are instated in the traffic light that capture digital images, identify the vehicle's number plate, and check whether the vehicle violated the traffic rules or not. All this process is related to image processing."
            "\n\nIntroduction"
            "\n\nPython Pillow module is built on top of PIL (Python Image Library). It is the essential modules for image processing in Python. But it is not supported by Python 3. But, we can use this module with the Python 3.x versions as PIL. It supports the variability of images such as jpeg, png, bmp, gif, ppm, and tiff."
            "\n\nWe can do anything on the digital images using the pillow module. In the upcoming section, we will learn various operations on the images such as filtering images, Creating thumbnail, merging images, cropping images, blur an image, resizing an image, creating a water mark and many other operations."
            "\n\nInstallation of Pillow"
            "\n\nBefore start working with Python, we need to install the pillow library to our local machine. We can do it by typing the following command in the terminal."
            "\n\npip install pillo"
            "\nor"
            "\npip install PI"
            "\n\nIf pip is already installed in the system, it will simply show the requirement already satisfied.",
        Url:
            "https://static.javatpoint.com/tutorial/python-pillow/images/python-pillow.png",
        Name: "Python Pillow");
    webview PythonTurtle = webview(
        Nameint: "Python Turtle Programming",
        info:
            "Turtle is a Python library which used to create graphics, pictures, and games. It was developed by Wally Feurzeig, Seymour Parpet and Cynthina Slolomon in 1967. It was a part of the original Logo programming language."
            "\n\nThe Logo programming language was popular among the kids because it enables us to draw attractive graphs to the screen in the simple way. It is like a little object on the screen, which can move according to the desired position. Similarly, turtle library comes with the interactive feature that gives the flexibility to work with Python."
            "\n\nIn this tutorial, we will learn the basic concepts of the turtle library, how to set the turtle up on a computer, programming with the Python turtle library, few important turtle commands, and develop a short but attractive design using the Python turtle library."
            "\n\nIntroduction"
            "\n\nTurtle is a pre-installed library in Python that is similar to the virtual canvas that we can draw pictures and attractive shapes. It provides the onscreen pen that we can use for drawing."
            "\n\nThe turtle Library is primarily designed to introduce children to the world of programming. With the help of Turtle's library, new programmers can get an idea of how we can do programming with Python in a fun and interactive way."
            "\n\nIt is beneficial to the children and for the experienced programmer because it allows designing unique shapes, attractive pictures, and various games. We can also design the mini games and animation. In the upcoming section, we will learn to various functionality of turtle library."
            "\n\nGetting started with turtle"
            "\n\nBefore working with the turtle library, we must ensure the two most essential things to do programming."
            "\n\nPython Environment - We must be familiar with the working Python environment. We can use applications such as IDLE or Jupiter Notebook. We can also use the Python interactive shell"
            "\n\nPython Version - We must have Python 3 in our system; if not, then download it from Python's official website."
            "\n\nThe turtle is built in library so we don't need to install separately. We just need to import the library into our Python environment."
            "\n\nThe Python turtle library consists of all important methods and functions that we will need to create our designs and images. Import the turtle library using the following command."
            "\n\nimport turtle"
            "\n\nNow, we can access all methods and functions. First, we need to create a dedicated window where we carry out each drawing command. We can do it by initializing a variable for it."
            "\n\ns = turtle.getscreen()"
            "\n\nIt will look like an above image and the little triangle in the middle of the screen is a turtle. If the screen is not appearing in your computer system, use the below code."
            "\n\nExample -"
            "\n\nimport turtle"
            "\n\n# Creating turtle screen"
            "\n\n s = turtle.getscreen()"
            "\n\n# To stop the screen to display"
            "\n\n turtle.mainloop()"
            "\n\nThe screen same as the canvas and turtle acts like a pen. You can move the turtle to design the desired shape. The turtle has certain changeable features such as color, speed, and size. It can be moved to a specific direction, and move in that direction unless we tell it otherwise."
            "\n\nIn the next section, we will learn to program with the Python turtle library.",
        Url:
            "https://qph.cf2.quoracdn.net/main-qimg-3727d03c3cca5432919458acb7029aa2-lq",
        Name: "Python Turtle");
    list.add(splunk);
    list.add(SPSS);
    list.add(Swagger);
    list.add(Transact);
    list.add(Tumbir);
    list.add(ReactJS);
    list.add(Regesx);
    list.add(ReinforcementLearning);
    list.add(RProgramming);
    list.add(RxJS);
    list.add(ReactNative);
    list.add(PythonDesign);
    list.add(PythonPillow);
    list.add(PythonTurtle);
    return list;
  }

  List<webview> Wikilist() {
    List<webview> list = [];
    webview Eng = webview(
      Language: "WikipediA",
      Name: "English",
      Nameint: "6 644 000+",
      info: "articles",
    );
    webview rus = webview(
      Language: "Википедия",
      Name: "русский",
      Nameint: "1 909 000+",
      info: "статей",
    );
    webview jap = webview(
      Language: "ウィキペディア",
      Name: "日本語",
      Nameint: "1 370 000+",
      info: "記事",
    );
    webview Deutsch = webview(
      Language: "WkipediA",
      Name: "Deutsch",
      Nameint: "2 792 000+",
      info: "Artikel",
    );
    webview Espaol = webview(
      Language: "WkipediA",
      Name: "Español",
      Nameint: "1 854 000+",
      info: "artículos",
    );
    webview Franais = webview(
      Language: "WikipédiA",
      Name: "Français",
      Nameint: "2 514 000+",
      info: "articles",
    );
    webview Italiano = webview(
      Language: "WkipediA",
      Name: "Italiano",
      Nameint: "1 806 000+",
      info: "voci",
    );
    webview chinese = webview(
      Language: "维基百科",
      Name: "中文",
      Nameint: "1 347 000+",
      info: "条目 / 條目",
    );
    webview arabic = webview(
      Language: "ویکی‌پدیا",
      Name: "فارسی",
      Nameint: "959 000+",
      info: "مقاله",
    );
    webview porto = webview(
      Language: "WikipédiA",
      Name: "Português",
      Nameint: "1 101 000+",
      info: "artigos",
    );
    list.add(Eng);
    list.add(rus);
    list.add(jap);
    list.add(Deutsch);
    list.add(Espaol);
    list.add(Franais);
    list.add(Italiano);
    list.add(chinese);
    list.add(arabic);
    list.add(porto);
    return list;
  }

  List<webview> wiki4() {
    List<webview> list = [];
    webview wikimediacommon = webview(
      Name: "Commons",
      Nameint: "Freely usable",
      Image:
          "https://www.wikimedia.fr/wp-content/uploads/2017/04/Stickers-Commons.png",
      info: "photos & more",
    );
    webview wikimediacommon1 = webview(
      Name: "wikivoyage",
      Nameint: "Free travel guide",
      Image:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Wikivoyage-logo.svg/2048px-Wikivoyage-logo.svg.png",
      info: "",
    );
    webview wikimediacommon2 = webview(
      Name: "Wiktionary",
      Nameint: "Free dictionary",
      Image:
          "https://p7.hiclipart.com/preview/939/8/920/wiktionary-wikimedia-foundation-html-others.jpg",
      info: "",
    );
    webview wikimediacommon3 = webview(
      Name: "Wikibooks",
      Nameint: "Free textbooks",
      Image:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Wikibooks-logo-background.png/720px-Wikibooks-logo-background.png",
      info: "",
    );
    webview wikimediacommon4 = webview(
      Name: "Wikinews",
      Nameint: "Free news source",
      Image:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Wikinews-logo.svg/1200px-Wikinews-logo.svg.png",
      info: "",
    );
    webview wikimediacommon5 = webview(
      Name: "Wikidata",
      Nameint: "Free knowledge",
      Image:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wikidata-logo.svg/2560px-Wikidata-logo.svg.png",
      info: "base",
    );
    list.add(wikimediacommon);
    list.add(wikimediacommon1);
    list.add(wikimediacommon2);
    list.add(wikimediacommon3);
    list.add(wikimediacommon4);
    list.add(wikimediacommon5);
    return list;
  }
}
